### PR TITLE
Style fix

### PR DESCRIPTION
**Pull request by DimaSmagulov**
code review:
- [ ] @CHILL99 
- [x] @krisberry 
- [x] @natalya5 
- [x] @oleg08 
- [x] @OrestF 
- [x] @rtershak 
- [x] @vvs79 

2nd lvl review:

- [ ] @Kmalynss
- [ ] @serhiym 
- [x] @ruba-ruba

https://trello.com/c/8X5SP1Ei/29-bootstrap-styles-for-all-pages

### CODE REVIEW

**Comment by Kmalynss** [comment]
Please add link to task in trello

**Comment by OrestF** [comment]
Reviewed by me!

**Comment by vvs79** [comment]
I reviewed this PR

**Comment by natalya5** [comment]
reviewed

**Comment by oleg08** [comment]
reviewed

**Comment by krisberry** [comment]
reviewed

**Comment by rtershak** [comment]
reviewed.

**Pull request merged**
