### PR TITLE
Fix bug

### PR DESCRIPTION
**Pull request by DimaSmagulov**
code review:
- [x] @CHILL99 
- [x] @krisberry 
- [x] @natalya5 
- [ ] @oleg08 
- [x] @OrestF 
- [ ] @rtershak 
- [x] @vvs79 

2nd lvl review:

- [ ] @Kmalynss
- [ ] @serhiym 
- [ ] @ruba-ruba

### CODE REVIEW

**Comment by vvs79** [comment]
reviewed

**Comment by OrestF** [comment]
reviewed

**Comment by natalya5** [comment]
reviewed

**Comment by CHILL99** [comment]
reviewed

**Comment by serhiym** [comment]
lgtm
FYI @Kmalynss

**Pull request merged**
