### PR TITLE
Auth page: need to fix position of checkbox "Remember me"

### PR DESCRIPTION
**Pull request by rtershak**
code review:
- [ ] @CHILL99 
- [x] @DimaSmagulov 
- [ ] @krisberry 
- [ ] @natalya5 
- [x] @oleg08 
- [x] @OrestF 
- [x] @vvs79 

2nd lvl review:

- [x] @Kmalynss
- [ ] @serhiym 
- [ ] @ruba-ruba

### CODE REVIEW

**Comment by vvs79** [comment]
reviewed

**Comment by OrestF** [comment]
I have no remarks:)

**Comment by DimaSmagulov** [comment]
+

**Comment by oleg08** [comment]
ok

**Comment by Kmalynss** [comment]
gtg

**Comment by Kmalynss** [comment]
BTW is good practice to use ids only with js

**Pull request merged**
