### PR TITLE
Finish covering question functionality with tests

### PR DESCRIPTION
**Pull request by CHILL99**
code review:
- [x] @DimaSmagulov 
- [x] @krisberry 
- [x] @natalya5 
- [x] @oleg08 
- [x] @OrestF 
- [ ] @rtershak 
- [x] @vvs79 

2nd lvl review:

- [x] @Kmalynss
- [ ] @serhiym 
- [ ] @ruba-ruba

### CODE REVIEW

**Comment by OrestF** [comment]
reviewed

**Comment by DimaSmagulov** [comment]
reviewed

**Comment by krisberry** [comment]
reviewed

**Comment by oleg08** [comment]
reviewed

**Comment by vvs79** [comment]
reviewed

**Comment by natalya5** [comment]
reviewed

**Pull request merged**
