### PR TITLE
Topic-tests

### PR DESCRIPTION
**Pull request by DimaSmagulov**
code review:
- [ ] @CHILL99 
- [ ] @krisberry 
- [x] @natalya5 
- [x] @oleg08 
- [x] @OrestF 
- [x] @rtershak 
- [x] @vvs79 

2nd lvl review:

- [ ] @Kmalynss
- [ ] @serhiym 
- [ ] @ruba-ruba

https://trello.com/c/XIcRaCLf/25-cover-topics-functionality-with-tests

1.Tests for topics
2. Added error messages on pages
3. Added rescue ActiveRecord::RecordNotFound for question :show and :edit
4. Last merge failed to build on heroku, so fixed config/aws.yml section for `production`
5. Fixed config/aws.yml section for `test`
6.Some style fixes.

### CODE REVIEW

**Comment by vvs79** [comment]
reviewed

**Comment by oleg08** [comment]
reviewed

**Comment by natalya5** [comment]
reviewed

**Comment by rtershak** [comment]
reviewed.

**Comment by OrestF** [comment]
Reviewed

**Comment by Kmalynss** [comment]
:+1:

**Pull request merged**
